plugins {
    id "com.android.application"
}

android {
    namespace "au.com.ldcs.flexdisplay.rook"
    compileSdk 33

    defaultConfig {
        applicationId "au.com.ldcs.flexdisplay.rook"
        minSdk 24
        targetSdk 33
        versionCode 5
        versionName "0.5.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
